### ISSUE TITLE
TypeError: Cannot read property 'handleConnectionClosed' of null

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#105]
This error (chat crash) ocurred after leaving a chat room open for some time during testing. A few clients and a counselor had connected to the chat previously. Relates to #94 @alex-bukach.
```
/home/demo/domains/demo-node.curachat.com/opeka/nodejs/lib/client.js:108
        self.server.handleConnectionClosed(self);
                   ^

TypeError: Cannot read property 'handleConnectionClosed' of null
    at Client.self.onConnectionClosed (/home/demo/domains/demo-node.curachat.com/opeka/nodejs/lib/client.js:108:20)
    at D.<anonymous> (/home/demo/domains/demo-node.curachat.com/opeka/nodejs/lib/client.js:64:18)
    at emitNone (events.js:91:20)
    at D.emit (events.js:185:7)
    at D.dnode.end (/home/demo/domains/demo-node.curachat.com/opeka/nodejs/node_modules/dnode/lib/dnode.js:148:10)
    at D.dnode.destroy (/home/demo/domains/demo-node.curachat.com/opeka/nodejs/node_modules/dnode/lib/dnode.js:152:10)
    at SockJSConnection.onclose (stream.js:67:50)
    at emitNone (events.js:91:20)
    at SockJSConnection.emit (events.js:185:7)
    at cleanup (/home/demo/domains/demo-node.curachat.com/opeka/nodejs/node_modules/shoe/index.js:25:20)
```

**Comment by alex-bukach** [comment]
@benjamin-dk I cannot reproduce it right away. Could you give more details? Were you able to reproduce the issue?

**Comment by cfdp** [comment]
@alex-bukach I have just reproduced the issue. I created a group chat room, connected with two clients, simulating connection losses etc. I left the chat in an erroneous state described in #108 for around 10 minutes.

**Comment by cfdp** [comment]
We haven't seen this for a long time so closing
