### ISSUE TITLE
Cannot read property ‘user’ of undefined

### ISSUE THREAD

**Issue by DanielMM** [cfdp/opeka#12]
We found this error in the console output during one group chat sessions.

[Type Error: Cannot read property ‘user’ of undefined]
Type Error: Cannot read property ‘user’ of undefined
	at [object Object].<anonymous> (/home/cyberhus/opeka/lib/opeka.js:317:41)
at [object Object].<anonymous> (native)
at Socket.efcHandler (/home/cyberhus/opeka/node_modules/now/lib/user.js:111:19)
at Socket.$emit (events.js:67:17)
at SocketNamespace.handlePacket (/home/cyberhus/opeka/node_modules/now/node_modules/socket.io/lib/namespace.js:335:22)
at Manager.onClientMessage (/home/cyberhus/opeka/node_modules/now/node_modules/socket.io/lib/manager.js:468:38)
at WebSocket.onMessage (/home/cyberhus/opeka/node_modules/now/node_modules/socket.io/lib/transport.js:387:20)
at Parser.<anonymous> (/home/cyberhus/opeka/node_modules/now/node_modules/socket.io/lib/transports/websocket/default.js:37:10)
at Parser.emit (events.js:67:17)
at Parser.parse (/home/cyberhus/opeka/node_modules/now/node_modules/socket.io/lib/transports/websocket/default.js:341:12)

**Comment by benjamin-dk** [comment]
No activity for a long time, so closing
