### ISSUE TITLE
TypeError: room.removeUser is not a function

### ISSUE THREAD

**Issue by gvd1** [cfdp/opeka#128]
```
 Mar 11:58:24 - Admin user added to room 32a7959b-9917-4732-b2e4-7e575b193821
2018-03-22T11:58:24.502Z - info: Login: User chat start:  25361998
2018-03-22T11:58:24.503Z - info: removeUserFromRoom, clientId: 8b1c358e-65e9-48a2-800b-98534cd3b9ca , admin?  undefined
2018-03-22T11:58:24.503Z - info: User left room: Chat duration (minutes):  0
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: room.removeUser is not a function
    at Server.self.removeUserFromRoom (/home/<username>/domains/<username>-node.curachat.com/opeka/nodejs/lib/opeka.js:1290:12)
    at Client.<anonymous> (/home/<username>/domains/<username>-node.curachat.com/opeka/nodejs/lib/opeka.js:961:14)
    at methods.(anonymous function) (/home/<username>/domains/<username>-node.curachat.com/opeka/nodejs/lib/groups.js:200:24)
    at Proto.apply (/home/ubuntu/.nvm/versions/node/v6.6.0/lib/node_modules/dnode/node_modules/dnode-protocol/index.js:123:13)
    at Proto.handle (/home/ubuntu/.nvm/versions/node/v6.6.0/lib/node_modules/dnode/node_modules/dnode-protocol/index.js:99:19)
    at D.dnode.handle (/home/ubuntu/.nvm/versions/node/v6.6.0/lib/node_modules/dnode/lib/dnode.js:140:21)
    at D.dnode.write (/home/ubuntu/.nvm/versions/node/v6.6.0/lib/node_modules/dnode/lib/dnode.js:128:22)
    at SockJSConnection.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at SockJSConnection.emit (events.js:188:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
```

**Comment by benjamin-dk** [comment]
this error is still present
```

2018-06-11T16:59:59.532Z - info: User left room: Chat duration (minutes):  0
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: room.removeUser is not a function
    at Server.self.removeUserFromRoom (/home/<username>/domains/<username>-node.curachat.com/opeka/nodejs/lib/opeka.js:1399:10)
    at Client.<anonymous> (/home/<username>/domains/<username>-node.curachat.com/opeka/nodejs/lib/opeka.js:1035:14)
    at methods.(anonymous function) (/home/<username>/domains/<username>-node.curachat.com/opeka/nodejs/lib/groups.js:203:24)
    at Proto.apply (/home/ubuntu/.nvm/versions/node/v6.6.0/lib/node_modules/dnode/node_modules/dnode-protocol/index.js:123:13)
    at Proto.handle (/home/ubuntu/.nvm/versions/node/v6.6.0/lib/node_modules/dnode/node_modules/dnode-protocol/index.js:99:19)
    at D.dnode.handle (/home/ubuntu/.nvm/versions/node/v6.6.0/lib/node_modules/dnode/lib/dnode.js:140:21)
    at D.dnode.write (/home/ubuntu/.nvm/versions/node/v6.6.0/lib/node_modules/dnode/lib/dnode.js:128:22)
    at SockJSConnection.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at SockJSConnection.emit (events.js:188:7)
```
