### ISSUE TITLE
Chat app freeze after deletion of rooms

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#34]
Testing the app on the 20th of january 2014, we experienced that the app froze - the sign in button to the app was not responding.

This happened under the following conditions (appr.)

* chat started with forever script
* two counselors signed in
* a few chats had taken place with anonymous users (connecting via external IP and local IP)
* the two rooms were deleted by the counselors

It was not possible to reproduce the error systematically.

The issue might be related to the error report that was found in the forever log:

```
20 Jan 10:12:53 - Regular user added to room ad5280a9-fa85-4e61-be7b-2087db9cd0e9
2014-01-20T10:15:09.290Z - ^[[32minfo^[[39m: Logout: User chat start:  23170213
2014-01-20T10:15:09.292Z - ^[[32minfo^[[39m: Logout: User chat end:  23170215
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /home/ubuntu/programs/node_modules/drupal/lib/db.js:130:7
    at Query.Client.query (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/client.js:106:11)
    at Query.EventEmitter.emit (events.js:96:17)
    at Query._handlePacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/query.js:29:12)
    at Client._handlePacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/client.js:319:14)
    at Parser.EventEmitter.emit (events.js:96:17)
    at Parser.write.emitPacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/parser.js:71:14)
    at Parser.write (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/parser.js:576:7)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:397:14)
2014-01-20T10:15:09.790Z - ^[[32minfo^[[39m: User disconnected. VAm1ZjxeTIwQblTw07kv
```

**Comment by benjamin-dk** [comment]
Closing this since we haven't seen it since it was first reported.
