### ISSUE TITLE
TypeError: Property 'displayError' of object #<Object> is not a function

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#37]
`2014-03-04T13:47:04.483Z - [32minfo[39m: Room Chatrum (50632e23-b69a-4584-8d4a-238ec94abbef) deleted.
[TypeError: Property 'displayError' of object #<Object> is not a function]
TypeError: Property 'displayError' of object #<Object> is not a function
    at self.councellors.now.deleteRoom (/home/ubuntu/programs/cfdpchat/nodejs/lib/opeka.js:555:16)
    at Socket.rfcHandler (/home/ubuntu/programs/node_modules/now/lib/user.js:111:19)
    at Socket.EventEmitter.emit [as $emit] (events.js:96:17)
    at SocketNamespace.handlePacket (/home/ubuntu/programs/node_modules/now/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/ubuntu/programs/node_modules/now/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/home/ubuntu/programs/node_modules/now/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/ubuntu/programs/node_modules/now/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
    at Parser.EventEmitter.emit (events.js:96:17)
    at opcodeHandlers.1.finish (/home/ubuntu/programs/node_modules/now/node_modules/socket.io/lib/transports/websocket/hybi-16.js:288:16)
    at Parser.opcodeHandlers.1.expectData [as expectHandler] (/home/ubuntu/programs/node_modules/now/node_modules/socket.io/lib/transports/websocket/hybi-16.js:299:15)`

**Comment by benjamin-dk** [comment]
Hasn't been seen for a while so closing
