### ISSUE TITLE
Not able to log in to chat, chat could not be restarted

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#41]
A counselor could not log into the chat to close it after deleting a chat room.

She was presented with the login form at

`/admin/opeka`

but the app was unresponsive when clicking the "Ready to chat" button. It was not possible to restart the chat via the admin interface.

Log file:

`2015-01-26T20:00:20.229Z - ^[[32minfo^[[39m: Room Rygestop - tips og tricks (1e0b4b6d-68fe-402f-acae-24caa7d9ce25) deleted.
2015-01-26T20:00:23.246Z - ^[[32minfo^[[39m: Admin user disconnected. VGjH7gnH7dXiQhYMlNFO
warn: client not handshaken client should reconnect
warn: client not handshaken client should reconnect
warn: client not handshaken client should reconnect
warn: client not handshaken client should reconnect
warn: client not handshaken client should reconnect
warn: client not handshaken client should reconnect
warn: websocket parser error: no handler for opcode 10
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /home/ubuntu/programs/node_modules/drupal/lib/db.js:130:7
    at Query.Client.query (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/client.js:106:11)
    at Query.EventEmitter.emit (events.js:96:17)
    at Query._handlePacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/query.js:29:12)
    at Client._handlePacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/client.js:319:14)
    at Parser.EventEmitter.emit (events.js:96:17)
    at Parser.write.emitPacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/parser.js:71:14)
    at Parser.write (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/parser.js:576:7)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:397:14)
warn: websocket parser error: no handler for opcode 10
warn: websocket parser error: no handler for opcode 10
warn: websocket parser error: no handler for opcode 10
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /home/ubuntu/programs/node_modules/drupal/lib/db.js:130:7
    at Query.Client.query (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/client.js:106:11)
    at Query.EventEmitter.emit (events.js:96:17)
    at Query._handlePacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/query.js:29:12)
    at Client._handlePacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/client.js:319:14)
    at Parser.EventEmitter.emit (events.js:96:17)
    at Parser.write.emitPacket (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/parser.js:71:14)
    at Parser.write (/home/ubuntu/programs/node_modules/drupal/node_modules/mysql/lib/parser.js:576:7)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:397:14)
2015-01-27T10:17:57.046Z - ^[[32minfo^[[39m: Connecting to database...
2015-01-27T10:17:57.147Z - ^[[32minfo^[[39m: Opeka chat server listening on port 3002
2015-01-27T10:20:28.558Z - ^[[32minfo^[[39m: User that can generate ban codes signed in. uKMlf2ymm34o1aGY5cij
2015-01-27T10:20:28.559Z - ^[[32minfo^[[39m: Admin user signed in. uKMlf2ymm34o1aGY5cij
2015-01-27T10:21:16.996Z - ^[[32minfo^[[39m: Admin user disconnected. uKMlf2ymm34o1aGY5cij`

**Comment by benjamin-dk** [comment]
No activity for a long time so closing
