### ISSUE TITLE
Banning a user in the group chat causes chat to crash

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#50]
This error might be related

2015-11-26T18:12:49.220Z - ^[[32minfo^[[39m: Logout: User chat end:  24142693

/usr/lib/node_modules/drupal/lib/db.js:130
      callback(err, result);
      ^
TypeError: undefined is not a function
    at /usr/lib/node_modules/drupal/lib/db.js:130:7
    at Query.<anonymous> (/usr/lib/node_modules/drupal/node_modules/mysql/lib/client.js:106:11)
    at Query.emit (events.js:95:17)
    at Query._handlePacket (/usr/lib/node_modules/drupal/node_modules/mysql/lib/query.js:29:12)
    at Client._handlePacket (/usr/lib/node_modules/drupal/node_modules/mysql/lib/client.js:319:14)
    at Parser.emit (events.js:95:17)
    at emitPacket (/usr/lib/node_modules/drupal/node_modules/mysql/lib/parser.js:71:14)
    at Parser.write (/usr/lib/node_modules/drupal/node_modules/mysql/lib/parser.js:576:7)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
error: Forever detected script exited with code: 8

**Comment by benjamin-dk** [comment]
Fixed in commit 4fd4eb80acc67cd20
