### ISSUE TITLE
[Error: connect ECONNREFUSED]

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#51]
25 May 18:01:58 - Admin user added to room 03c0e001-d5f6-466d-b971-ac3fa9ddefce
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
error: Forever detected script exited with code: 143
error: Script restart attempt #1

TypeError: Cannot call method 'forEach' of null
    at /home/kbhchat/opeka/nodejs/lib/ban.js:70:12
    at /usr/lib/node_modules/drupal/lib/db.js:126:7
    at Query.query.on.on.fields.(anonymous function) (/usr/lib/node_modules/drupal/node_modules/mysql/lib/client.js:95:9)
    at Query.emit (events.js:95:17)
    at Client.<anonymous> (/usr/lib/node_modules/drupal/node_modules/mysql/lib/client.js:349:16)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #2

TypeError: Cannot call method 'forEach' of null
    at /home/kbhchat/opeka/nodejs/lib/ban.js:70:12
    at /usr/lib/node_modules/drupal/lib/db.js:126:7
    at Query.query.on.on.fields.(anonymous function) (/usr/lib/node_modules/drupal/node_modules/mysql/lib/client.js:95:9)
    at Query.emit (events.js:95:17)
    at Client.<anonymous> (/usr/lib/node_modules/drupal/node_modules/mysql/lib/client.js:349:16)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #3

**Comment by cfdp** [comment]
Havent seen this for a while, so closing
