### ISSUE TITLE
Prepare input for db storage

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/opeka#83]
The screening questions and answers should be stored in the db but at the moment I am struggling to find the right syntax for saving the array.

```
19 Apr 10:43:56 - Error: Screening responses could not be saved.
/home/demo/opeka/nodejs/node_modules/mysql/lib/protocol/Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'questions' in 'field list'
    at Query.Sequence._packetToError (/home/demo/opeka/nodejs/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
    at Query.ErrorPacket (/home/demo/opeka/nodejs/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/demo/opeka/nodejs/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/demo/opeka/nodejs/node_modules/mysql/lib/protocol/Parser.js:74:12)

```
The screening question module should be enabled,and the screeningQuestions setting should be set to true in config.json.

**Comment by cfdp** [comment]
Fixed with #84
