### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#91]
```
2017-05-18T15:18:30.156Z - info: Admin user disconnected. 31fee822-1ae5-4df1-ac5e-e67e287e21e7
2017-05-18T15:18:30.157Z - info: Logout: User chat start:  24918677
2017-05-18T15:18:30.157Z - info: Logout: User chat end:  24918679
2017-05-18T15:18:30.158Z - warning: Last admin user disconnected - shutting down room. Counselor id:  31fee822-1ae5-4df1-ac5e-e67e287e21e7
/home/halsnaes/domains/halsnaes-node.curachat.com/opeka/nodejs/lib/opeka.js:1138
      checkPause = (activeRoomId === room.id);
                                         ^

TypeError: Cannot read property 'id' of undefined
    at Server.self.removeUserFromRoom (/home/halsnaes/domains/halsnaes-node.curachat.com/opeka/nodejs/lib/opeka.js:1138:42)
    at /home/halsnaes/domains/halsnaes-node.curachat.com/opeka/nodejs/lib/opeka.js:1073:14
    at Array.forEach (native)
    at /home/halsnaes/domains/halsnaes-node.curachat.com/opeka/nodejs/lib/opeka.js:1057:37
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error: Forever detected script exited with code: 1
```

**Comment by cfdp** [comment]
duplicate of #46
